# Generated by Django 5.1.5 on 2025-01-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_id_alter_like_id_alter_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
