# Generated by Django 5.1.5 on 2025-01-25 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_like_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(blank=True, help_text='The article that was liked, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='app.article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='The user who liked the article or comment.', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
