# Generated by Django 5.1.5 on 2025-01-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_article_image_link_remove_article_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.CharField(default=1, help_text='The introduction of the article.', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The title of the article.', max_length=50),
        ),
    ]
